# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_completo', models.CharField(max_length=80)),
                ('ra', models.CharField(default='1762126', max_length=11, unique=True)),
                ('contato', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Professores',
                'verbose_name': 'Professor',
            },
            bases=('conta.user',),
        ),
    ]
