# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(default='Ano Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('sigla', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'verbose_name': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('nome', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('apelido', models.SlugField(unique=True)),
                ('carga_horario', models.PositiveSmallIntegerField()),
                ('teoria', models.CharField(max_length=500)),
                ('pratica', models.CharField(max_length=500)),
                ('ementa', models.TextField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField()),
                ('conteudo', models.TextField()),
                ('bibliografia_basica', models.TextField()),
                ('bibliografia_complementar', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'verbose_name': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('Manhã', 'Matutino'), ('Noite', 'Noturno')], max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Periodos',
                'verbose_name': 'Periodo',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='Semestre do Curso', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Semestres',
                'verbose_name': 'Semestre Ano',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('turma_id', models.AutoField(primary_key=True, serialize=False)),
                ('apelido_turma', models.SlugField(unique=True, verbose_name='Apelido da Turma')),
                ('alunos', models.ManyToManyField(to='aluno.Aluno', verbose_name='Alunos')),
                ('ano', models.ManyToManyField(to='curso.Ano', verbose_name='Ano Letivo da Turma')),
                ('grade_materias_turma', models.ManyToManyField(to='curso.Disciplinas', verbose_name='Grade Curricular do Semestre')),
                ('periodo', models.ManyToManyField(to='curso.Periodo', verbose_name='Periodo da Turma')),
                ('semestre', models.ManyToManyField(to='curso.Semestre', verbose_name='Semestre da Turma')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'verbose_name': 'Turma',
            },
        ),
    ]
